'./spec/features/appearance/theme_spec.rb[1:1]':
  name: "Theme 01"
  environment_variables:
    FEATURE_NAME: "Theme 01"
    FEATURE: './spec/features/appearance/theme_spec.rb[1:1]'
'./spec/features/appearance/theme_spec.rb[1:2]':
  name: "Theme 02"
  environment_variables:
    FEATURE_NAME: "Theme 02"
    FEATURE: './spec/features/appearance/theme_spec.rb[1:2]'
'./spec/features/appearance/theme_spec.rb[1:3]':
  name: "Theme 03"
  environment_variables:
    FEATURE_NAME: "Theme 03"
    FEATURE: './spec/features/appearance/theme_spec.rb[1:3]'
'./spec/features/entitlement-groups/create_spec.rb[1:1]':
  name: "Create entitlement group 01"
  environment_variables:
    FEATURE_NAME: "Create entitlement group 01"
    FEATURE: './spec/features/entitlement-groups/create_spec.rb[1:1]'
'./spec/features/entitlement-groups/create_spec.rb[1:2]':
  name: "Create entitlement group 02"
  environment_variables:
    FEATURE_NAME: "Create entitlement group 02"
    FEATURE: './spec/features/entitlement-groups/create_spec.rb[1:2]'
'./spec/features/entitlement-groups/create_spec.rb[1:3]':
  name: "Create entitlement group 03"
  environment_variables:
    FEATURE_NAME: "Create entitlement group 03"
    FEATURE: './spec/features/entitlement-groups/create_spec.rb[1:3]'
'./spec/features/entitlement-groups/delete_spec.rb[1:1]':
  name: "Delete entitlement group 01"
  environment_variables:
    FEATURE_NAME: "Delete entitlement group 01"
    FEATURE: './spec/features/entitlement-groups/delete_spec.rb[1:1]'
'./spec/features/entitlement-groups/delete_spec.rb[1:2]':
  name: "Delete entitlement group 02"
  environment_variables:
    FEATURE_NAME: "Delete entitlement group 02"
    FEATURE: './spec/features/entitlement-groups/delete_spec.rb[1:2]'
'./spec/features/entitlement-groups/list_spec.rb[1:1]':
  name: "List entitlement groups 01"
  environment_variables:
    FEATURE_NAME: "List entitlement groups 01"
    FEATURE: './spec/features/entitlement-groups/list_spec.rb[1:1]'
'./spec/features/entitlement-groups/update_spec.rb[1:1]':
  name: "Update entitlement group 01"
  environment_variables:
    FEATURE_NAME: "Update entitlement group 01"
    FEATURE: './spec/features/entitlement-groups/update_spec.rb[1:1]'
'./spec/features/error-handling/application_errors_spec.rb[1:1]':
  name: "Application Errors 01"
  environment_variables:
    FEATURE_NAME: "Application Errors 01"
    FEATURE: './spec/features/error-handling/application_errors_spec.rb[1:1]'
'./spec/features/error-handling/client_errors_spec.rb[1:1]':
  name: "Client Errors 01"
  environment_variables:
    FEATURE_NAME: "Client Errors 01"
    FEATURE: './spec/features/error-handling/client_errors_spec.rb[1:1]'
'./spec/features/error-handling/client_errors_spec.rb[1:2]':
  name: "Client Errors 02"
  environment_variables:
    FEATURE_NAME: "Client Errors 02"
    FEATURE: './spec/features/error-handling/client_errors_spec.rb[1:2]'
'./spec/features/error-handling/network_errors_spec.rb[1:1]':
  name: "Network Errors 01"
  environment_variables:
    FEATURE_NAME: "Network Errors 01"
    FEATURE: './spec/features/error-handling/network_errors_spec.rb[1:1]'
'./spec/features/i18n/language-switcher_spec.rb[1:1]':
  name: "Language 01"
  environment_variables:
    FEATURE_NAME: "Language 01"
    FEATURE: './spec/features/i18n/language-switcher_spec.rb[1:1]'
'./spec/features/i18n/language-switcher_spec.rb[1:2]':
  name: "Language 02"
  environment_variables:
    FEATURE_NAME: "Language 02"
    FEATURE: './spec/features/i18n/language-switcher_spec.rb[1:2]'
'./spec/features/i18n/language-switcher_spec.rb[1:3]':
  name: "Language 03"
  environment_variables:
    FEATURE_NAME: "Language 03"
    FEATURE: './spec/features/i18n/language-switcher_spec.rb[1:3]'
'./spec/features/inventory-list/duplicate_item_spec.rb[1:1]':
  name: "Duplicate Item from Inventory List 01"
  environment_variables:
    FEATURE_NAME: "Duplicate Item from Inventory List 01"
    FEATURE: './spec/features/inventory-list/duplicate_item_spec.rb[1:1]'
'./spec/features/inventory-list/main_spec.rb[1:1]':
  name: "Inventory Page 01"
  environment_variables:
    FEATURE_NAME: "Inventory Page 01"
    FEATURE: './spec/features/inventory-list/main_spec.rb[1:1]'
'./spec/features/inventory-list/main_spec.rb[1:2]':
  name: "Inventory Page 02"
  environment_variables:
    FEATURE_NAME: "Inventory Page 02"
    FEATURE: './spec/features/inventory-list/main_spec.rb[1:2]'
'./spec/features/inventory-list/pagination_spec.rb[1:1]':
  name: "Inventory Pagination 01"
  environment_variables:
    FEATURE_NAME: "Inventory Pagination 01"
    FEATURE: './spec/features/inventory-list/pagination_spec.rb[1:1]'
'./spec/features/inventory-list/pagination_spec.rb[1:2]':
  name: "Inventory Pagination 02"
  environment_variables:
    FEATURE_NAME: "Inventory Pagination 02"
    FEATURE: './spec/features/inventory-list/pagination_spec.rb[1:2]'
'./spec/features/items/batch_create_spec.rb[1:1]':
  name: "Batch create items 01"
  environment_variables:
    FEATURE_NAME: "Batch create items 01"
    FEATURE: './spec/features/items/batch_create_spec.rb[1:1]'
'./spec/features/items/create_spec.rb[1:1]':
  name: "Create item 01"
  environment_variables:
    FEATURE_NAME: "Create item 01"
    FEATURE: './spec/features/items/create_spec.rb[1:1]'
'./spec/features/items/create_spec.rb[1:2]':
  name: "Create item 02"
  environment_variables:
    FEATURE_NAME: "Create item 02"
    FEATURE: './spec/features/items/create_spec.rb[1:2]'
'./spec/features/items/create_spec.rb[1:3]':
  name: "Create item 03"
  environment_variables:
    FEATURE_NAME: "Create item 03"
    FEATURE: './spec/features/items/create_spec.rb[1:3]'
'./spec/features/items/create_spec.rb[1:4]':
  name: "Create item 04"
  environment_variables:
    FEATURE_NAME: "Create item 04"
    FEATURE: './spec/features/items/create_spec.rb[1:4]'
'./spec/features/items/update_spec.rb[1:1]':
  name: "Update item 01"
  environment_variables:
    FEATURE_NAME: "Update item 01"
    FEATURE: './spec/features/items/update_spec.rb[1:1]'
'./spec/features/items/update_spec.rb[1:2]':
  name: "Update item 02"
  environment_variables:
    FEATURE_NAME: "Update item 02"
    FEATURE: './spec/features/items/update_spec.rb[1:2]'
'./spec/features/items/update_spec.rb[1:3]':
  name: "Update item 03"
  environment_variables:
    FEATURE_NAME: "Update item 03"
    FEATURE: './spec/features/items/update_spec.rb[1:3]'
'./spec/features/models/create_spec.rb[1:1]':
  name: "Create model 01"
  environment_variables:
    FEATURE_NAME: "Create model 01"
    FEATURE: './spec/features/models/create_spec.rb[1:1]'
'./spec/features/models/create_spec.rb[1:2]':
  name: "Create model 02"
  environment_variables:
    FEATURE_NAME: "Create model 02"
    FEATURE: './spec/features/models/create_spec.rb[1:2]'
'./spec/features/models/create_spec.rb[1:3]':
  name: "Create model 03"
  environment_variables:
    FEATURE_NAME: "Create model 03"
    FEATURE: './spec/features/models/create_spec.rb[1:3]'
'./spec/features/models/create_spec.rb[1:4]':
  name: "Create model 04"
  environment_variables:
    FEATURE_NAME: "Create model 04"
    FEATURE: './spec/features/models/create_spec.rb[1:4]'
'./spec/features/models/delete_spec.rb[1:1]':
  name: "Delete model 01"
  environment_variables:
    FEATURE_NAME: "Delete model 01"
    FEATURE: './spec/features/models/delete_spec.rb[1:1]'
'./spec/features/models/delete_spec.rb[1:2]':
  name: "Delete model 02"
  environment_variables:
    FEATURE_NAME: "Delete model 02"
    FEATURE: './spec/features/models/delete_spec.rb[1:2]'
'./spec/features/models/update_spec.rb[1:1]':
  name: "Update model 01"
  environment_variables:
    FEATURE_NAME: "Update model 01"
    FEATURE: './spec/features/models/update_spec.rb[1:1]'
'./spec/features/models/update_spec.rb[1:2]':
  name: "Update model 02"
  environment_variables:
    FEATURE_NAME: "Update model 02"
    FEATURE: './spec/features/models/update_spec.rb[1:2]'
'./spec/features/models/update_spec.rb[1:3]':
  name: "Update model 03"
  environment_variables:
    FEATURE_NAME: "Update model 03"
    FEATURE: './spec/features/models/update_spec.rb[1:3]'
'./spec/features/options/create_spec.rb[1:1]':
  name: "Create option 01"
  environment_variables:
    FEATURE_NAME: "Create option 01"
    FEATURE: './spec/features/options/create_spec.rb[1:1]'
'./spec/features/options/create_spec.rb[1:2]':
  name: "Create option 02"
  environment_variables:
    FEATURE_NAME: "Create option 02"
    FEATURE: './spec/features/options/create_spec.rb[1:2]'
'./spec/features/options/create_spec.rb[1:3]':
  name: "Create option 03"
  environment_variables:
    FEATURE_NAME: "Create option 03"
    FEATURE: './spec/features/options/create_spec.rb[1:3]'
'./spec/features/options/create_spec.rb[1:4]':
  name: "Create option 04"
  environment_variables:
    FEATURE_NAME: "Create option 04"
    FEATURE: './spec/features/options/create_spec.rb[1:4]'
'./spec/features/options/delete_spec.rb[1:1]':
  name: "Delete option 01"
  environment_variables:
    FEATURE_NAME: "Delete option 01"
    FEATURE: './spec/features/options/delete_spec.rb[1:1]'
'./spec/features/options/delete_spec.rb[1:2]':
  name: "Delete option 02"
  environment_variables:
    FEATURE_NAME: "Delete option 02"
    FEATURE: './spec/features/options/delete_spec.rb[1:2]'
'./spec/features/options/update_spec.rb[1:1]':
  name: "Update option 01"
  environment_variables:
    FEATURE_NAME: "Update option 01"
    FEATURE: './spec/features/options/update_spec.rb[1:1]'
'./spec/features/packages/create_spec.rb[1:1]':
  name: "Create package 01"
  environment_variables:
    FEATURE_NAME: "Create package 01"
    FEATURE: './spec/features/packages/create_spec.rb[1:1]'
'./spec/features/packages/create_spec.rb[1:2]':
  name: "Create package 02"
  environment_variables:
    FEATURE_NAME: "Create package 02"
    FEATURE: './spec/features/packages/create_spec.rb[1:2]'
'./spec/features/packages/create_spec.rb[1:3]':
  name: "Create package 03"
  environment_variables:
    FEATURE_NAME: "Create package 03"
    FEATURE: './spec/features/packages/create_spec.rb[1:3]'
'./spec/features/packages/create_spec.rb[1:4]':
  name: "Create package 04"
  environment_variables:
    FEATURE_NAME: "Create package 04"
    FEATURE: './spec/features/packages/create_spec.rb[1:4]'
'./spec/features/packages/update_spec.rb[1:1]':
  name: "Update package 01"
  environment_variables:
    FEATURE_NAME: "Update package 01"
    FEATURE: './spec/features/packages/update_spec.rb[1:1]'
'./spec/features/packages/update_spec.rb[1:2]':
  name: "Update package 02"
  environment_variables:
    FEATURE_NAME: "Update package 02"
    FEATURE: './spec/features/packages/update_spec.rb[1:2]'
'./spec/features/packages/update_spec.rb[1:3]':
  name: "Update package 03"
  environment_variables:
    FEATURE_NAME: "Update package 03"
    FEATURE: './spec/features/packages/update_spec.rb[1:3]'
'./spec/features/packages/update_spec.rb[1:4]':
  name: "Update package 04"
  environment_variables:
    FEATURE_NAME: "Update package 04"
    FEATURE: './spec/features/packages/update_spec.rb[1:4]'
'./spec/features/root_page_smoke_spec.rb[1:1:1]':
  name: "Root page renders 01"
  environment_variables:
    FEATURE_NAME: "Root page renders 01"
    FEATURE: './spec/features/root_page_smoke_spec.rb[1:1:1]'
'./spec/features/sign_in_out_spec.rb[1:1:1:1]':
  name: "Sign-in / Sign-out works sign-in with invalid credentials 01"
  environment_variables:
    FEATURE_NAME: "Sign-in / Sign-out works sign-in with invalid credentials 01"
    FEATURE: './spec/features/sign_in_out_spec.rb[1:1:1:1]'
'./spec/features/sign_in_out_spec.rb[1:1:2:1]':
  name: "Sign-in / Sign-out works sign-in/out with valid credentials 01"
  environment_variables:
    FEATURE_NAME: "Sign-in / Sign-out works sign-in/out with valid credentials 01"
    FEATURE: './spec/features/sign_in_out_spec.rb[1:1:2:1]'
'./spec/features/sign_in_out_spec.rb[1:1:2:2]':
  name: "Sign-in / Sign-out works sign-in/out with valid credentials 02"
  environment_variables:
    FEATURE_NAME: "Sign-in / Sign-out works sign-in/out with valid credentials 02"
    FEATURE: './spec/features/sign_in_out_spec.rb[1:1:2:2]'
'./spec/features/software/create_spec.rb[1:1]':
  name: "Create software 01"
  environment_variables:
    FEATURE_NAME: "Create software 01"
    FEATURE: './spec/features/software/create_spec.rb[1:1]'
'./spec/features/software/create_spec.rb[1:2]':
  name: "Create software 02"
  environment_variables:
    FEATURE_NAME: "Create software 02"
    FEATURE: './spec/features/software/create_spec.rb[1:2]'
'./spec/features/software/create_spec.rb[1:3]':
  name: "Create software 03"
  environment_variables:
    FEATURE_NAME: "Create software 03"
    FEATURE: './spec/features/software/create_spec.rb[1:3]'
'./spec/features/software/create_spec.rb[1:4]':
  name: "Create software 04"
  environment_variables:
    FEATURE_NAME: "Create software 04"
    FEATURE: './spec/features/software/create_spec.rb[1:4]'
'./spec/features/software/delete_spec.rb[1:1]':
  name: "Delete software 01"
  environment_variables:
    FEATURE_NAME: "Delete software 01"
    FEATURE: './spec/features/software/delete_spec.rb[1:1]'
'./spec/features/software/delete_spec.rb[1:2]':
  name: "Delete software 02"
  environment_variables:
    FEATURE_NAME: "Delete software 02"
    FEATURE: './spec/features/software/delete_spec.rb[1:2]'
'./spec/features/software/update_spec.rb[1:1]':
  name: "Update software 01"
  environment_variables:
    FEATURE_NAME: "Update software 01"
    FEATURE: './spec/features/software/update_spec.rb[1:1]'
'./spec/features/swagger/smoke_spec.rb[1:1:1]':
  name: "Swagger renders 01"
  environment_variables:
    FEATURE_NAME: "Swagger renders 01"
    FEATURE: './spec/features/swagger/smoke_spec.rb[1:1:1]'
'./spec/features/templates/create_spec.rb[1:1]':
  name: "Create template 01"
  environment_variables:
    FEATURE_NAME: "Create template 01"
    FEATURE: './spec/features/templates/create_spec.rb[1:1]'
'./spec/features/templates/create_spec.rb[1:2]':
  name: "Create template 02"
  environment_variables:
    FEATURE_NAME: "Create template 02"
    FEATURE: './spec/features/templates/create_spec.rb[1:2]'
'./spec/features/templates/create_spec.rb[1:3]':
  name: "Create template 03"
  environment_variables:
    FEATURE_NAME: "Create template 03"
    FEATURE: './spec/features/templates/create_spec.rb[1:3]'
'./spec/features/templates/delete_spec.rb[1:1]':
  name: "Delete template 01"
  environment_variables:
    FEATURE_NAME: "Delete template 01"
    FEATURE: './spec/features/templates/delete_spec.rb[1:1]'
'./spec/features/templates/delete_spec.rb[1:2]':
  name: "Delete template 02"
  environment_variables:
    FEATURE_NAME: "Delete template 02"
    FEATURE: './spec/features/templates/delete_spec.rb[1:2]'
'./spec/features/templates/update_spec.rb[1:1]':
  name: "Update template 01"
  environment_variables:
    FEATURE_NAME: "Update template 01"
    FEATURE: './spec/features/templates/update_spec.rb[1:1]'
