#!/usr/bin/env bash

for TREE in 'constants' 'password-authentication.back' 'password-authentication.front' \
  'paths' 'session' 'sign-in.front' 'sign-out' 'utils.anti-csrf.back' 'utils.anti-csrf.front' \
  'utils.core' 'utils.json' 'utils.json-protocol' 'utils.query-params' 'utils.sql'

do 
  egrep -R -l "leihs.${TREE}"  src/ leihs-clj-shared/src/ | xargs -o -I {} vim "+%s/leihs.${TREE}/leihs.core.${TREE}/gI" '+wq' {}
done 


