#!/usr/bin/env bash

SNS=$1

if [[ -z $SNS ]]; then 
  exit -1
fi

egrep -R -l "leihs.admin.utils.$SNS"  src/ | xargs -o -I {} vim "+%s/\vleihs.admin.utils.$SNS/leihs.core.$SNS/gI" '+wq' {}


egrep -R -l "leihs.admin.utils.$SNS"  src/ | xargs -o -I {} vim "+%s/\vleihs.admin.utils.$SNS/leihs.core.$SNS/gI" '+wq' {}

